name: "Cleanup CI"

on:
  # run weekly on Monday at 12:00
  schedule:
    - cron: '0 12 * * 1'
  # run manually
  workflow_dispatch:

jobs:
  cleanup:
    name: 'Sync Repository Configuration'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: '.'

    permissions:
      contents: read

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Node - Setup
        id: node_setup
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: NPM - Install Dependencies
        id: npm_install
        run: npm ci

      - name: NPM - Cleanup Repository
        id: npm_run_cleanup
        run: npm run cleanup

      - name: GitHub - Generate App Token
        id: github_generate_app_token
        uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06 # tag=v1.6.0
        with:
          app_id: ${{ secrets.REPOSITORY_ASSISTANT_APP_ID }}
          private_key: ${{ secrets.REPOSITORY_ASSISTANT_PRIVATE_KEY }}

      - name: GitHub - Setup GPG Keys
        id: github_setup_gpg
        uses: crazy-max/ghaction-import-gpg@c8bb57c57e8df1be8c73ff3d59deab1dbc00e0d1 # tag=v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Git - Commit and Push State Changes
        id: git_commit_push
        uses: stefanzweifel/git-auto-commit-action@6c32682a4040e023c054b2fc60a7cf65cc77f7ad # tag=v4
        with:
          commit_message: "chore: cleanup repository [skip ci]"
          commit_options: --no-verify
          commit_user_name: ${{ steps.github_setup_gpg.outputs.name }}
          commit_user_email: ${{ steps.github_setup_gpg.outputs.email }}
          commit_author: repository-assistant[bot] <${{ secrets.REPOSITORY_ASSISTANT_APP_ID }}+repository-assistant[bot]@users.noreply.github.com>
          file_pattern: ./state/**
