name: "Cleanup CI"

on:
  # run weekly on Monday at 12:00
  schedule:
    - cron: '0 12 * * 1'
  # run manually
  workflow_dispatch:

jobs:
  cleanup_pulumi_state:
    name: 'Cleanup Pulumi State'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: '.'

    permissions:
      contents: read

    steps:
      - name: StepSecurity - Harden Github-hosted Runners
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit
          disable-telemetry: true
          disable-sudo: true

      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          # https://github.com/marketplace/actions/git-auto-commit#checkout-the-correct-branch
          ref: ${{ github.head_ref }}
          # this is the token that the "git-auto-commit" action is using, so we use the one from the app
          # https://github.com/marketplace/actions/git-auto-commit#commits-made-by-this-action-do-not-trigger-new-workflow-runs
          token: ${{ secrets.GH_AUTOMATION_TOKEN }}

      - name: Node - Setup
        id: node_setup
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: NPM - Install Dependencies
        id: npm_install
        run: npm ci

      - name: NPM - Cleanup Pulumi State
        id: npm_run_cleanup
        run: npm run cleanup

      - name: GitHub - Setup GPG Keys
        id: github_setup_gpg
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # v6.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Git - Commit and Push State Changes
        id: git_commit_push
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        with:
          commit_message: "chore: cleanup repository [skip ci]"
          commit_options: --no-verify
          commit_user_name: ${{ steps.github_setup_gpg.outputs.name }}
          commit_user_email: ${{ steps.github_setup_gpg.outputs.email }}
          commit_author: repository-assistant[bot] <${{ secrets.REPOSITORY_ASSISTANT_APP_ID }}+repository-assistant[bot]@users.noreply.github.com>
          file_pattern: ./state/**
