name: "Cleanup CI"

on:
  # run weekly on Monday at 12:00
  schedule:
    - cron: '0 12 * * 1'
  # run manually
  workflow_dispatch:

jobs:
  cleanup_pulumi_state:
    name: 'Cleanup Pulumi State'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: '.'

    permissions:
      contents: read

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
        with:
          # https://github.com/marketplace/actions/git-auto-commit#checkout-the-correct-branch
          ref: ${{ github.head_ref }}
          # this is the token that the "git-auto-commit" action is using, so we use the one from the app
          # https://github.com/marketplace/actions/git-auto-commit#commits-made-by-this-action-do-not-trigger-new-workflow-runs
          token: ${{ secrets.GH_AUTOMATION_TOKEN }}

      - name: Node - Setup
        id: node_setup
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: NPM - Install Dependencies
        id: npm_install
        run: npm ci

      - name: NPM - Cleanup Pulumi State
        id: npm_run_cleanup
        run: npm run cleanup

      - name: GitHub - Setup GPG Keys
        id: github_setup_gpg
        uses: crazy-max/ghaction-import-gpg@c8bb57c57e8df1be8c73ff3d59deab1dbc00e0d1 # tag=v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Git - Commit and Push State Changes
        id: git_commit_push
        uses: stefanzweifel/git-auto-commit-action@fd157da78fa13d9383e5580d1fd1184d89554b51 # tag=v4
        with:
          commit_message: "chore: cleanup repository [skip ci]"
          commit_options: --no-verify
          commit_user_name: ${{ steps.github_setup_gpg.outputs.name }}
          commit_user_email: ${{ steps.github_setup_gpg.outputs.email }}
          commit_author: repository-assistant[bot] <${{ secrets.REPOSITORY_ASSISTANT_APP_ID }}+repository-assistant[bot]@users.noreply.github.com>
          file_pattern: ./state/**
