name: "Code CI"

on:
  # run on pushes to main
  push:
    branches:
      - main
      - gh-readonly-queue/main/**
  # run on pull requests that target the main branch
  pull_request:
    branches:
      - main
  # run weekly on Monday at 12:00
  schedule:
    - cron: '0 12 * * 1'

concurrency:
  # on main, we want all builds to complete even if commits/merging happens faster to make it easier to discover at which point
  # something broke; else, we cancel "old" builds and run/(re)start the build with the latest changes
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}-{1}', github.workflow, github.sha) || format('ci-{0}-{1}', github.workflow, github.ref) }}

jobs:
  codeql_analyze:
    name: 'CodeQL - Analyze'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: '.'

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        # https://git.io/codeql-language-support
        language: ['javascript']

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      # Initializes the CodeQL tools for scanning.
      - name: CodeQL - Initialization
        id: codeql_initialization
        uses: github/codeql-action/init@e0e5ded33cabb451ae0a9768fc7b0410bad9ad44 # tag=v2.1.26
        with:
          languages: ${{ matrix.language }}
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.
          # queries: ./path/to/local/query, your-org/your-repo/queries@main

      - name: CodeQL - Autobuild
        id: codeql_autobuild
        uses: github/codeql-action/autobuild@e0e5ded33cabb451ae0a9768fc7b0410bad9ad44 # tag=v2.1.26

      - name: CodeQL - Analysis
        id: codeql_analysis
        uses: github/codeql-action/analyze@e0e5ded33cabb451ae0a9768fc7b0410bad9ad44 # tag=v2.1.26

  typecheck:
    name: 'TypeScript - Type Check'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: '.'

    permissions:
      contents: read

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Node - Setup
        id: node_setup
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Just - Setup
        uses: extractions/setup-just@95b912dc5d3ed106a72907f2f9b91e76d60bdb76 # tag=v1
        with:
          just-version: '^1.1.2'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: NPM - Install Dependencies
        id: npm_install
        run: npm ci

      - name: TypeScript - Type Check
        id: typescript_typecheck
        run: just typecheck

  unit_tests:
    name: 'Jest - Unit Tests'
    runs-on: ubuntu-latest

    env:
      JUNIT_TEST_RESULTS_FILE: ./.test_results_junit.xml

    defaults:
      run:
        shell: bash
        working-directory: '.'

    permissions:
      contents: read

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Node - Setup
        id: node_setup
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Just - Setup
        uses: extractions/setup-just@95b912dc5d3ed106a72907f2f9b91e76d60bdb76 # tag=v1
        with:
          just-version: '^1.1.2'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: NPM - Install Dependencies
        id: npm_install
        run: npm ci

      - name: Jest - Unit Tests
        id: jest_unit_tests
        run: just test_ci --coverage --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_FILE: ${{ env.JUNIT_TEST_RESULTS_FILE }}

      - name: GitHub - Generate App Token
        id: github_generate_app_token
        uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06 # tag=v1.6.0
        if: always()
        with:
          # https://github.com/EnricoMi/publish-unit-test-result-action/issues/161
          app_id: ${{ secrets.UNIT_TEST_RESULTS_REPORTER_APP_ID }}
          private_key: ${{ secrets.UNIT_TEST_RESULTS_REPORTER_PRIVATE_KEY }}

      - name: GitHub - Publish Unit Test Results
        id: github_publish_results
        uses: EnricoMi/publish-unit-test-result-action@b9f6c61d965bcaa18acc02d6daf706373a448f02 # tag=v1.40
        if: always()
        with:
          github_token: ${{ steps.github_generate_app_token.outputs.token }}
          check_name: Test Results
          files: ${{ env.JUNIT_TEST_RESULTS_FILE }}
          # we only add github checks to the PR/commit, but don't create PR comments; reason is that comments will not
          # be replaced but always newly added due to (it looks for "github-actions" user instead of the github app user):
          # https://github.com/EnricoMi/publish-unit-test-result-action/blob/ae7c14a87cf1a1200805b487debc65963bdb3f2d/python/publish/publisher.py#L493
          comment_mode: off

      - name: Codecov - Upload Coverage Data
        id: codecov_upload_data
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          flags: unittests
          env_vars: RUNNER_OS,RUNNER_ARCH,GITHUB_EVENT_NAME
          fail_ci_if_error: true
          verbose: true
